### ISSUE TITLE
Deepthought don't works in Linux, but works in Windows

### ISSUE THREAD

**Issue by TehDmitry** [rubenlagus/Deepthougth#24]
Same jar with same Java "1.8.0_121" works in different ways in Windows and Linux.
Sometimes in Linux works fine, sometimes got timeouts in startup.
In Windows always all works fine.

**In Linux**

```
{FINE} TELEGRAMAPI - >> #0: updates.getState#edd4882a
{FINE} TELEGRAMAPI - #> #0 sent to MTProto #1001 with id #2
{FINE} MTPROTO - Client connected: 1
{FINE} MTPROTO - Received data 218
FINE} MTPROTO - Received data 185
{FINE} MTPROTO - org.telegram.mtproto.transport.TcpContext@7c4382be Received message len 216 equal to packet size
{FINE} MTPROTO - Decrypted in 1 ms
{FINE} TELEGRAMAPI - #> #1 sent to MTProto #1001 with id #5
{WARNING} TELEGRAMAPI - updates.getState#edd4882a
{SEVERE} TELEGRAMAPI - java.util.concurrent.TimeoutException	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:358)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:332)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:450)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:437)
	at org.telegram.bot.kernel.KernelComm.lambda$doRpcCallSync$0(KernelComm.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

{SEVERE} KERNELCOMM - java.util.concurrent.TimeoutException	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:358)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:332)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:450)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:437)
	at org.telegram.bot.kernel.KernelComm.lambda$doRpcCallSync$0(KernelComm.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**In Windows**
```
{FINE} TELEGRAMAPI - >> #0: updates.getState#edd4882a
{FINE} TELEGRAMAPI - #> #0 sent to MTProto #1001 with id #2
{FINE} MTPROTO - Client connected: 1
{FINE} MTPROTO - Received data 186
{FINE} MTPROTO - org.telegram.mtproto.transport.TcpContext@5908fb8e Received message len 184 equal to packet size
{FINE} MTPROTO - Decrypted in 0 ms
{FINE} TELEGRAMAPI - >> #1: updates.getState#edd4882a
{FINE} TELEGRAMAPI - << #0 confirmed in 327 ms
```

[full Windows log](http://pastebin.com/hFfiBsAN)
[full Linux log](http://pastebin.com/iDb3xGrw)

**Comment by TehDmitry** [comment]
https://github.com/rubenlagus/TelegramApi/issues/19

**Comment by dapoldi** [comment]
Hey there, this isn't an actual issue (at least not on our side), just the way a blocking entropy provider works, a workaround is indeed using dev/urandom, although less secure.

With enough entropy available dev/random will work nicely. Windows uses a non blocking provider by default.

Using the not-so-very-secure urandom by default would be bad practice. (We could wait longer, but in some cases this may end up being days, for those systems it's wise to either use the urandom workaround or install something like rng-tools).

Going to close this one.

**Comment by dapoldi** [comment]
Closed: use  -Djava.security.egd=file:/dev/./urandom as workaround for systems with a lack of entropy or install rng-tools.

**Comment by amin1softco** [comment]
imagine honeypot from telegram team 🗡

**Comment by yoricya** [comment]
> [rubenlagus/TelegramApi#19](https://github.com/rubenlagus/TelegramApi/issues/19)

Help plz, It doesn't work on macOS
