### ISSUE TITLE
error on invite user to channel

### ISSUE THREAD

**Issue by saffari-m** [rubenlagus/Deepthougth#26]
hi guys
i will try to add user to channel with userId. 
but i have blow error.
no body have any idea??

*i'm channel creator.*

> ERROR

`org.telegram.api.engine.RpcException: USER_ID_INVALID
	at org.telegram.api.engine.TelegramApi$2.onError(TelegramApi.java:345)
	at org.telegram.api.engine.TelegramApi$ProtoCallback.onRpcError(TelegramApi.java:851)
	at org.telegram.mtproto.MTProto.onMTProtoMessage(MTProto.java:375)
	at org.telegram.mtproto.MTProto.onMTMessage(MTProto.java:255)
	at org.telegram.mtproto.MTProto.access$1300(MTProto.java:44)
	at org.telegram.mtproto.MTProto$ResponseProcessor.run(MTProto.java:754)`

`org.telegram.api.engine.RpcException: PEER_FLOOD
	at org.telegram.api.engine.TelegramApi$2.onError(TelegramApi.java:345)
	at org.telegram.api.engine.TelegramApi$ProtoCallback.onRpcError(TelegramApi.java:851)
	at org.telegram.mtproto.MTProto.onMTProtoMessage(MTProto.java:375)
	at org.telegram.mtproto.MTProto.onMTMessage(MTProto.java:255)
	at org.telegram.mtproto.MTProto.access$1300(MTProto.java:44)
	at org.telegram.mtproto.MTProto$ResponseProcessor.run(MTProto.java:754)
`

>MyCode

```TLRequestChannelsInviteToChannel inviteToChannel = new TLRequestChannelsInviteToChannel();
TLVector<TLAbsInputUser> userTLVector;
List<User> users = kernelService.databaseManager.getUser();
for (User user : users) {
	userTLVector = new TLVector<>();
	TLInputUser inputUser = new TLInputUser();
	inputUser.setUserId(user.getUserId());
	inputUser.setAccessHash(user.getUserHash());
	userTLVector.add(inputUser);
	inviteToChannel.setUsers(userTLVector);
	TLInputChannel tlInputChannel = new TLInputChannel();
	tlInputChannel.setChannelId(1146442581);
	tlInputChannel.setAccessHash(8344840662564112189L);
	inviteToChannel.setChannel(tlInputChannel);
	kernelService.kernel.getKernelComm().getApi().doRpcCall(inviteToChannel);
}

>Sample of users table

userId      |     userHash
----------------------------------------------
35528688;   |  -4124795944391814318
60298992;   |   3603661406479113586
68340652;   |
77415017;   |   1332773656954829334
96964919;   |
113071326;  |   -8811764397750991599
115916915;  |   8275589059187648032
121874181;  |   3498714609031911456
124417043;  |   8705010231588220910
169614878;  |  -6545612745507802927

```

**Comment by rubenlagus** [comment]
`PEER_FLOOD` is because you are hitting limits
`USER_ID_INVALID` usually means that the user can't be added to the channel.

Does it happen with every user or only with some of them? Have you also tested with different channels?
