### ISSUE TITLE
It doens't send code

### ISSUE THREAD

**Issue by ali-imanpour** [rubenlagus/Deepthougth#27]
Hello,
When I run project, it doesn't send code, and I get below output.
What's problem?
```

INFO: [KERNELAUTH] Sending code to phone ...
Jul 02, 2017 11:25:12 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1001: onSessionCreated
Jul 02, 2017 11:25:17 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] auth.sendCode#86aef0ec
Jul 02, 2017 11:25:17 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] #4: Creating key
Jul 02, 2017 11:25:47 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] auth.sendCode#86aef0ec
Jul 02, 2017 11:25:47 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.KernelAuth started in 36397 ms
Jul 02, 2017 11:25:47 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.MainHandler init in 7 ms
Jul 02, 2017 11:25:47 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] ----------------BOT READY-----------------
Jul 02, 2017 11:26:16 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] updates.getState#edd4882a
Jul 02, 2017 11:26:16 AM org.telegram.bot.services.BotLogger log
SEVERE: KERNELCOMM
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:351)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:326)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:439)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:426)
	at org.telegram.bot.kernel.KernelComm.lambda$doRpcCallSync$0(KernelComm.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 02, 2017 11:26:16 AM org.telegram.bot.services.BotLogger severe
SEVERE: [KERNELHANDLER] Error getting updates state
Jul 02, 2017 11:30:12 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1004: onSessionCreated
Jul 02, 2017 11:30:24 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1003: onSessionCreated
```

**Comment by dapoldi** [comment]
Please have a look at:

https://github.com/rubenlagus/Deepthought/issues/24
https://github.com/rubenlagus/Deepthought/issues/19

You're probably on Linux with low entropy, add the extra startup parameter described in the closed issue referenced and shout if that doesn't fix it.
