### ISSUE TITLE
Timeout Exception after authentication

### ISSUE THREAD

**Issue by WOLFI3654** [rubenlagus/Deepthougth#29]
Hello,
I'm trying to run the Deepthought echo example but after I input my auth code into my console something is going wrong and I get an TimeoutException
`Aug 18, 2017 2:16:01 PM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] auth.signIn#bcd51581
Aug 18, 2017 2:16:23 PM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] updates.getState#edd4882a
Aug 18, 2017 2:16:23 PM org.telegram.bot.services.BotLogger log
SEVERE: KERNELCOMM
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:351)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:326)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:439)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:426)
	at org.telegram.bot.kernel.KernelComm.lambda$doRpcCallSync$0(KernelComm.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Aug 18, 2017 2:16:23 PM org.telegram.bot.services.BotLogger severe
SEVERE: [KERNELHANDLER] Error getting updates state
`

Have I configured something wrong?
(I have fixed linux random btw)

**Comment by pmouraguedes** [comment]
+1
I am getting exactly that and also used the linux random workaround. 
After receiving the auth code it gets a timeout.
Tested on a Ubuntu 16.04 box.

**Comment by pmouraguedes** [comment]
Hi again,

The program expects the auth code to be given as input in your console. After doing that I could successfully run it!

**Comment by fengyaojieTTT** [comment]
I also encountered this problem I don't know how to do! Have you solved it yet?
I tried setting up the JVM entropy pool, and it didn't seem to work for me at all! You'd better try it  
Can you tell me your solution?

**Comment by WOLFI3654** [comment]
@fengyaojie I remember something with the 2FA. I think I had to disable it or something like that. But not sure

**Comment by fengyaojieTTT** [comment]
@WOLFI3654 You still remember the specific code of operation friends can say a little bit more clearly how I should do it! Thank you!
